name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy-production:
    name: Deploy to Production
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    environment: MONGO_URI
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci
        env:
          NODE_ENV: production
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci
          
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
        env:
          REACT_APP_API_URL: http://localhost:${{ secrets.PORT }}
          CI: false

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          echo "Backend service running on port ${{ secrets.PORT }}"
          echo "Frontend built successfully"
          
      - name: Verify Deployment
        run: |
          echo "Verifying deployment..."
          echo "Application deployed successfully" 