name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Install backend dependencies
        working-directory: backend
        run: |
          npm ci
          echo "Backend dependencies installed successfully"

      - name: Run backend tests
        working-directory: backend
        run: |
          echo "Running backend tests..."
          npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
          NODE_ENV: test

      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          npm ci
          echo "Frontend dependencies installed successfully"

      - name: Build frontend
        working-directory: frontend
        run: |
          echo "Building frontend..."
          npm run build
        env:
          REACT_APP_API_URL: http://localhost:${{ secrets.PORT }}

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Build backend
        working-directory: backend
        run: |
          npm ci
          echo "Backend build successful"
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
          NODE_ENV: production

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
          echo "Frontend build successful"
        env:
          REACT_APP_API_URL: http://localhost:${{ secrets.PORT }}