name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - holidayfeatures
  pull_request:
    branches:
      - main
      - develop
      - holidayfeatures

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          npm ci
          echo "Backend dependencies installed successfully"

      - name: Create .env file for testing
        working-directory: backend
        run: |
          echo "MONGO_URI=mongodb://localhost:27017/holidayplanner-test" > .env.test
          echo "JWT_SECRET=test-secret-key" >> .env.test
          echo "PORT=5000" >> .env.test
          echo "NODE_ENV=test" >> .env.test

      - name: Run backend tests
        working-directory: backend
        run: |
          echo "Running backend tests..."
          NODE_ENV=test npm test
        env:
          MONGO_URI: mongodb://localhost:27017/holidayplanner-test
          JWT_SECRET: test-secret-key
          PORT: 5000
          NODE_ENV: test

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          npm ci
          echo "Frontend dependencies installed successfully"

      - name: Build frontend
        working-directory: frontend
        run: |
          echo "Building frontend..."
          npm run build
        env:
          REACT_APP_API_URL: http://localhost:5000

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Build backend
        working-directory: backend
        run: |
          npm ci
          echo "Backend build successful"
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
          echo "Frontend build successful"
        env:
          REACT_APP_API_URL: http://localhost:${{ secrets.PORT }}